-- Migración de persistencia de DatoPublico (FT00008).
--
-- Crea las tablas de dominio que usan los repositorios JDBC: `publicacion`,
-- `fragmento`, `resumen` y `cola_revision`. La extensión `vector` ya se habilita
-- en V1.
--
-- Diferido a propósito (no anticipar):
--   * la columna `embedding vector(384)` de `fragmento` y su índice HNSW → FT00016;
--   * los valores de `categoria` y `plazo_*` los rellena la clasificación → FT00012
--     (aquí las columnas existen y son nullable); el parser de FT00007 las deja nulas.
--
-- La escritura de `publicacion` es *upsert* por `id` (idempotencia de FT00009).

CREATE TABLE publicacion (
    id                 text PRIMARY KEY,
    titulo             text NOT NULL,
    fecha_publicacion  date NOT NULL,
    organismo          text,
    seccion            text NOT NULL,
    epigrafe           text,
    categoria          text,
    texto              text,
    url_oficial        text NOT NULL,
    url_xml            text,
    url_pdf            text,
    rango              text,
    plazo_fecha_limite date,
    plazo_descripcion  text,
    creado_en          timestamptz NOT NULL DEFAULT now(),
    actualizado_en     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX publicacion_fecha_publicacion_idx ON publicacion (fecha_publicacion);
CREATE INDEX publicacion_seccion_idx ON publicacion (seccion);
CREATE INDEX publicacion_categoria_idx ON publicacion (categoria);
CREATE INDEX publicacion_organismo_idx ON publicacion (organismo);

CREATE TABLE fragmento (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publicacion_id text NOT NULL REFERENCES publicacion (id) ON DELETE CASCADE,
    orden          integer NOT NULL,
    referencia     text,
    contenido      text NOT NULL,
    creado_en      timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT fragmento_publicacion_orden_unique UNIQUE (publicacion_id, orden)
);

CREATE TABLE resumen (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publicacion_id text NOT NULL UNIQUE REFERENCES publicacion (id) ON DELETE CASCADE,
    que_cambia     text NOT NULL,
    a_quien_afecta text NOT NULL,
    cifras_clave   text[] NOT NULL DEFAULT '{}',
    fuente_oficial text NOT NULL,
    aviso_ia       boolean NOT NULL DEFAULT true,
    estado         text NOT NULL DEFAULT 'pendiente',
    confianza      numeric,
    creado_en      timestamptz NOT NULL DEFAULT now(),
    actualizado_en timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE cola_revision (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resumen_id  bigint NOT NULL REFERENCES resumen (id) ON DELETE CASCADE,
    motivo      text,
    estado      text NOT NULL DEFAULT 'pendiente',
    creado_en   timestamptz NOT NULL DEFAULT now(),
    revisado_en timestamptz
);

CREATE INDEX cola_revision_estado_idx ON cola_revision (estado);
